Attribute VB_Name = "modNewsReaderEnum"
Option Explicit



'return codes
Public Enum TNNTPRc
    NNTP_RC_NONE = 0
    NNTP_RC_NOTCONNECTED = 1
    NNTP_RC_HOSTNOTFOUND = 2
    NNTP_RC_BUSY = 3
    NNTP_RC_SOCKERR = 4
    NNTP_RC_CANCELED = 5
    NNTP_RC_TIMEOUT = 6
    NNTP_RC_POSTING = 200
    NNTP_RC_NOPOSTING = 201
    NNTP_RC_CLOSING = 205
    NNTP_RC_GROUPSELECTED = 211
    NNTP_RC_LIST = 215
    NNTP_RC_ARTICLE = 220
    NNTP_RC_HEAD = 221
    NNTP_RC_BODY = 222
    NNTP_RC_STAT = 223
    NNTP_RC_DATAFOLLOWS = 224
    NNTP_RC_NEWARTICLES = 230
    NNTP_RC_NEWGROUPS = 231
    NNTP_RC_TRANSFERRED = 235
    NNTP_RC_POSTEDOK = 240
    NNTP_RC_AUTHENTICATIONACCEPTED = 281
    NNTP_RC_SENDARTICLETRANSFERRED = 335
    NNTP_RC_SENDARTICLE = 340
    NNTP_RC_MOREAUTHENTICATIONREQUIRED = 381
    NNTP_RC_SERVICEDISCONTINUED = 400
    NNTP_RC_NOSUCHNEWSGROUP = 411
    NNTP_RC_NOTINANEWSGROUP = 412
    NNTP_RC_NOARTICLESELECTED = 420
    NNTP_RC_NONEXTARTICLE = 421
    NNTP_RC_NOLASTARTICLE = 422
    NNTP_RC_BADARTICLENUMBER = 423
    NNTP_RC_ARTICLENOTFOUND = 430
    NNTP_RC_DONTSEND = 435
    NNTP_RC_TRANSFERFAILED = 436
    NNTP_RC_ARTICLEREJECTED = 437
    NNTP_RC_POSTINGNOTALLOWD = 440
    NNTP_RC_POSTINGFAILED = 441
    NNTP_RC_AUTHENTICATIONREQUIRED = 480
    NNTP_RC_AUTHENTICATIONREJECTED = 482
    NNTP_RC_NOSUCHCOMMAND = 500
    NNTP_RC_SYNTAXERROR = 501
    NNTP_RC_ACCESSRESTRICTED = 502
    NNTP_RC_PROGRAMNOTFAULT = 503
    NNTP_RC_CONNECTIONFAILURE1 = 504
    NNTP_RC_CONNECTIONFAILURE2 = 505
End Enum

